#!groovy

def awsRegion = "us-east-2"

pipeline {
    agent any

environment {
    AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    AWS_DEFAULT_REGION    = "{awsRegion}"
}

stages {
    stage("Terraform Init + Plan")
        steps {
            sh ''
                terraform init -no-color
                terraform plan -no-color
            ''
        }
    stage("Terraform Apply")
        steps {
            sh 'terraform apply -auto-approve'
        }
    }
}